services:
  api:
    build: .
    ports: ["8000:8000"]
    env_file: .env
    depends_on: [mongo]
    volumes:
      - ./secrets:/secrets:ro
    environment:
      - FIREBASE_CRED_PATH=/secrets/firebase.json

  mongo:
    image: mongo:7
    ports: ["27017:27017"]
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: fastapi_db

volumes:
  mongo_data:
